repository:
  url: https://github.com/BruninSouza/Ensino-Python
  branch: main

launch_buttons:
  notebook_path: "meu-livro" 
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

title: Estudos Python
author: Bruno Souza
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - docs/references.bib

html:
  use_issues_button: true
  use_repository_button: true
  theme: dark
  theme-light: light
  toggle_theme: true 
