name: build and deploy

on:
  push:
    branches:
      - main # ou master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install jupyter-book
          pip install -r requirements.txt # se você tiver um arquivo requirements.txt

      - name: Build the book
        run: jupyter-book build meu-livro/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: meu-livro/_build/html